version: '3.8'

services:
  database:
    container_name: database
    restart: on-failure:5
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-data:/var/lib/db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    container_name: api
    restart: on-failure:5
    build: 
      context: ./app
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    depends_on:
      database:
        condition: service_healthy

volumes:
  database-data:
